# FEATURE ENGINEERING(ENCODING)

- OneHotEncoder
- LabelEncoder
- BinaryEncoder
- BaseNencoder

In [3]:
import numpy as np 
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split 
%matplotlib inline

In [8]:
## loading dataset
df = pd.read_csv(r"C:\Users\P nageswararao\OneDrive\Desktop\mushrooms.csv")

In [9]:
df.head()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g

In [10]:
## Dataset info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   class                     8124 non-null   object
 1   cap-shape                 8124 non-null   object
 2   cap-surface               8124 non-null   object
 3   cap-color                 8124 non-null   object
 4   bruises                   8124 non-null   object
 5   odor                      8124 non-null   object
 6   gill-attachment           8124 non-null   object
 7   gill-spacing              8124 non-null   object
 8   gill-size                 8124 non-null   object
 9   gill-color                8124 non-null   object
 10  stalk-shape               8124 non-null   object
 11  stalk-root                8124 non-null   object
 12  stalk-surface-above-ring  8124 non-null   object
 13  stalk-surface-below-ring  8124 non-null   object
 14  stalk-color-above-ring    8124 non-null   object
 15  stalk-color-below-ring    8124 non-null   object
 16  veil-type                 8124 non-null   object
 17  veil-color                8124 non-null   object
 18  ring-number               8124 non-null   object
 19  ring-type                 8124 non-null   object
 20  spore-print-color         8124 non-null   object
 21  population                8124 non-null   object
 22  habitat                   8124 non-null   object
dtypes: object(23)
memory usage: 1.4+ MB

In [12]:
## Dataset descrption
df.describe().T

                         count unique top  freq
class                     8124      2   e  4208
cap-shape                 8124      6   x  3656
cap-surface               8124      4   y  3244
cap-color                 8124     10   n  2284
bruises                   8124      2   f  4748
odor                      8124      9   n  3528
gill-attachment           8124      2   f  7914
gill-spacing              8124      2   c  6812
gill-size                 8124      2   b  5612
gill-color                8124     12   b  1728
stalk-shape               8124      2   t  4608
stalk-root                8124      5   b  3776
stalk-surface-above-ring  8124      4   s  5176
stalk-surface-below-ring  8124      4   s  4936
stalk-color-above-ring    8124      9   w  4464
stalk-color-below-ring    8124      9   w  4384
veil-type                 8124      1   p  8124
veil-color                8124      4   w  7924
ring-number               8124      3   o  7488
ring-type                 8124      5   p  3968
spore-print-color         8124      9   w  2388
population                8124      6   v  4040
habitat                   8124      7   d  3148

In [13]:
## checking for null values
df.isnull().sum()

class                       0
cap-shape                   0
cap-surface                 0
cap-color                   0
bruises                     0
odor                        0
gill-attachment             0
gill-spacing                0
gill-size                   0
gill-color                  0
stalk-shape                 0
stalk-root                  0
stalk-surface-above-ring    0
stalk-surface-below-ring    0
stalk-color-above-ring      0
stalk-color-below-ring      0
veil-type                   0
veil-color                  0
ring-number                 0
ring-type                   0
spore-print-color           0
population                  0
habitat                     0
dtype: int64

In [14]:
## Dataset as Independent and Dependent features
X = df.iloc[:,1:]

In [16]:
X.shape

(8124, 22)

In [17]:
y = df.iloc[:,0]

In [19]:
y.shape

(8124,)

In [20]:
## splitting Dataset for Training and Testing
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [21]:
X_train.shape

(6499, 22)

In [23]:
y_train.shape

(6499,)

In [22]:
X_test.shape

(1625, 22)

In [24]:
y_test.shape

(1625,)

## OneHotEncoder

- In this technique, the categorical parameters will prepare separate columns for both Male and Female labels. So, wherever there is Male, the value will be 1 in Male column and 0 in Female column, and vice-versa. Letâ€™s understand with an example: Consider the data where fruits and their corresponding categorical values and prices are given.

In [25]:
## importing OneHot Encoding
from sklearn.preprocessing import OneHotEncoder

In [54]:
## creating an Object for OneHotEncoder
OE = OneHotEncoder(categories='auto',drop='first',sparse=False)

In [55]:
OE.fit(X_train)

OneHotEncoder(drop='first', sparse=False)

In [56]:
X_tr_encoded = OE.transform(X_train)

In [57]:
X_ts_encoded = OE.transform(X_test)

In [58]:
X_tr_encoded.shape

(6499, 95)

In [59]:
X_ts_encoded.shape

(1625, 95)

In [63]:
X_tr_encoded

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]])

In [61]:
X_ts_encoded

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.]])

# OrdinalEncoder

- In ordinal encoding, each unique category value is assigned an integer value.   
- This is called an ordinal encoding or an integer encoding and is easily reversible. Often, integer values starting at zero are used.

In [65]:
## importing ordinal encoder
from sklearn.preprocessing import OrdinalEncoder

In [66]:
## creating an object for OrdinalEncoder
OE  = OrdinalEncoder()

In [67]:
## fitting the train data
OE.fit(X_train)

OrdinalEncoder()

In [69]:
#transforming the train data
X_OE = OE.transform(X_train)

In [70]:
## traansforming thee test data
X_t_OE = OE.transform(X_test)

In [76]:
X_OE

array([[3., 2., 2., ..., 7., 4., 0.],
       [5., 2., 4., ..., 7., 4., 4.],
       [2., 3., 2., ..., 7., 4., 2.],
       ...,
       [2., 3., 4., ..., 3., 5., 4.],
       [3., 2., 2., ..., 7., 4., 4.],
       [3., 0., 3., ..., 7., 2., 1.]])

In [72]:
X_t_OE

array([[2., 0., 4., ..., 3., 3., 1.],
       [2., 2., 2., ..., 7., 4., 2.],
       [5., 3., 4., ..., 7., 4., 2.],
       ...,
       [5., 3., 4., ..., 7., 4., 4.],
       [3., 3., 4., ..., 7., 4., 4.],
       [5., 0., 9., ..., 1., 5., 4.]])

## LabelEcoder

- Label Encoder is used for encoding 1d data only                
- Label Encoding refers to converting the labels into a numeric form so as to convert them into the machine-readable form. Machine learning algorithms can then decide in a better way how those labels must be operated. It is an important pre-processing step for the structured dataset in supervised learning.

In [77]:
## importing Label Encoder
from sklearn.preprocessing import LabelEncoder

In [78]:
## creating the object for LabelEncoder
LE = LabelEncoder()

In [81]:
y_LE = LE.fit_transform(y_train)

In [82]:
y_LE

array([1, 1, 1, ..., 0, 1, 0])

## BinaryEncoding

- Binary encoding is a combination of Hash encoding and one-hot encoding. In this encoding scheme, the categorical feature is first converted into numerical using an ordinal encoder. Then the numbers are transformed in the binary number. After that binary value is split into different columns.

In [85]:
from category_encoders import BinaryEncoder

In [86]:
BE = BinaryEncoder()

In [87]:
X_BE = BE.fit_transform(X_train)

In [88]:
X_t_BE = BE.transform(X_test)

In [91]:
X_BE

,cap-shape_0,cap-shape_1,cap-shape_2,cap-surface_0,cap-surface_1,cap-surface_2,cap-color_0,cap-color_1,cap-color_2,cap-color_3,...,spore-print-color_0,spore-print-color_1,spore-print-color_2,spore-print-color_3,population_0,population_1,population_2,habitat_0,habitat_1,habitat_2
7873,0,0,1,0,0,1,0,0,0,1,...,0,0,0,1,0,0,1,0,0,1
6515,0,1,0,0,0,1,0,0,1,0,...,0,0,0,1,0,0,1,0,1,0
6141,0,1,1,0,1,0,0,0,0,1,...,0,0,0,1,0,0,1,0,1,1
2764,0,1,1,0,1,1,0,0,1,0,...,0,0,1,0,0,0,1,0,0,1
438,1,0,0,0,1,0,0,0,1,1,...,0,0,1,0,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5226,0,1,0,0,1,0,0,0,1,0,...,0,0,0,1,0,0,1,0,1,0
5390,0,0,1,0,1,0,0,0,0,1,...,0,0,0,1,1,0,0,1,0,1
860,0,1,1,0,1,0,0,0,1,0,...,0,0,1,0,0,1,1,0,1,0
7603,0,0,1,0,0,1,0,0,0,1,...,0,0,0,1,0,0,1,0,1,0
7270,0,0,1,0,1,1,0,1,0,0,...,0,0,0,1,0,1,0,1,1,1

In [92]:
X_t_BE

,cap-shape_0,cap-shape_1,cap-shape_2,cap-surface_0,cap-surface_1,cap-surface_2,cap-color_0,cap-color_1,cap-color_2,cap-color_3,...,spore-print-color_0,spore-print-color_1,spore-print-color_2,spore-print-color_3,population_0,population_1,population_2,habitat_0,habitat_1,habitat_2
1971,0,1,1,0,1,1,0,0,1,0,...,0,0,1,0,1,0,1,1,1,1
6654,0,1,1,0,0,1,0,0,0,1,...,0,0,0,1,0,0,1,0,1,1
5606,0,1,0,0,1,0,0,0,1,0,...,0,0,0,1,0,0,1,0,1,1
3332,0,1,1,0,1,0,0,1,0,0,...,0,0,1,0,0,1,1,0,0,1
6988,0,1,1,0,0,1,0,0,0,1,...,0,0,0,1,0,0,1,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7374,0,0,1,0,0,1,0,0,0,1,...,0,0,0,1,0,0,1,0,1,0
1149,0,1,1,0,0,1,0,0,1,0,...,0,1,0,0,1,1,0,1,1,1
4999,0,1,0,0,1,0,0,0,1,0,...,0,0,0,1,0,0,1,0,1,0
7497,0,0,1,0,1,0,0,0,1,0,...,0,0,0,1,0,0,1,0,1,0
3341,0,1,0,0,1,1,0,0,1,1,...,0,0,1,1,0,1,1,0,1,0

# Base N Encoding

- In the numeral system, the Base or the radix is the number of digits or a combination of digits and letters used to represent the numbers. The most common base we use in our life is 10  or decimal system as here we use 10 unique digits i.e 0 to 9 to represent all the numbers. Another widely used system is binary i.e. the base is 2. It uses 0 and 1 i.e 2 digits to express all the numbers.

In [100]:
from category_encoders import BaseNEncoder

In [102]:
BN = BaseNEncoder(return_df=True,base=7)

In [103]:
X_BN = BN.fit_transform(X_train)

In [104]:
X_t_BN = BN.transform(X_test)

In [105]:
X_BN

,cap-shape_0,cap-surface_0,cap-color_0,cap-color_1,bruises_0,odor_0,odor_1,gill-attachment_0,gill-spacing_0,gill-size_0,...,stalk-color-below-ring_1,veil-type_0,veil-color_0,ring-number_0,ring-type_0,spore-print-color_0,spore-print-color_1,population_0,habitat_0,habitat_1
7873,1,1,0,1,1,0,1,1,1,1,...,1,1,1,1,1,0,1,1,0,1
6515,2,1,0,2,1,0,2,1,1,1,...,1,1,1,1,1,0,1,1,0,2
6141,3,2,0,1,1,0,3,1,1,1,...,1,1,1,1,1,0,1,1,0,3
2764,3,3,0,2,2,0,4,1,1,2,...,2,1,1,1,2,0,2,1,0,1
438,4,2,0,3,2,0,5,1,1,2,...,1,1,1,1,2,0,2,2,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5226,2,2,0,2,1,0,2,1,1,1,...,1,1,1,1,1,0,1,1,0,2
5390,1,2,0,1,2,0,4,1,1,2,...,0,1,1,2,1,0,1,4,0,5
860,3,2,0,2,2,0,5,1,1,2,...,1,1,1,1,2,0,2,3,0,2
7603,1,1,0,1,1,0,2,1,1,1,...,2,1,1,1,1,0,1,1,0,2
7270,1,3,0,4,1,0,4,1,2,2,...,1,1,1,2,2,0,1,2,1,0

In [106]:
X_t_BN

,cap-shape_0,cap-surface_0,cap-color_0,cap-color_1,bruises_0,odor_0,odor_1,gill-attachment_0,gill-spacing_0,gill-size_0,...,stalk-color-below-ring_1,veil-type_0,veil-color_0,ring-number_0,ring-type_0,spore-print-color_0,spore-print-color_1,population_0,habitat_0,habitat_1
1971,3,3,0,2,1,0,4,1,2,2,...,1,1,1,1,1,0,2,5,1,0
6654,3,1,0,1,1,0,3,1,1,1,...,2,1,1,1,1,0,1,1,0,3
5606,2,2,0,2,1,0,2,1,1,1,...,2,1,1,1,1,0,1,1,0,3
3332,3,2,0,4,2,0,4,1,1,2,...,2,1,1,1,2,0,2,3,0,1
6988,3,1,0,1,1,0,1,1,1,1,...,2,1,1,1,1,0,1,1,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7374,1,1,0,1,1,0,2,1,1,1,...,1,1,1,1,1,0,1,1,0,2
1149,3,1,0,2,1,0,4,1,2,2,...,1,1,1,1,1,0,4,6,1,0
4999,2,2,0,2,1,0,2,1,1,1,...,2,1,1,1,1,0,1,1,0,2
7497,1,2,0,2,1,0,3,1,1,1,...,2,1,1,1,1,0,1,1,0,2
3341,2,3,0,3,1,0,2,1,1,2,...,4,1,1,1,3,0,3,3,0,2